export const brands = {
    "toni-and-guy": "Toni and Guy",
    "bblunt": "BBLUNT",
    "k-prives-salon": "K Prive's Salon",
    "shuddhi": "Shuddhi",
    "kaizo-salon-spa": "Kaizo Salon & Spa",
    "affinity-elite": "Affinity Elite",
    "harsha-rakesh": "Harsha Rakesh",
    "bodycraft": "Bodycraft",
    "juice": "Juice",
    "hair-look": "Hair Look",
    "lookwell": "LookWell",
    "brushes-and-strokes": "Brushes and Strokes",
    "looks": "Looks",
    "hq-salons": "HQ Salons",
    "hair-stories": "Hair Stories",
    "carezza-beauty": "Carezza Beauty",
    "yuan": "Yuan",
    "lemon": "Lemon",
    "tip-and-toe": "Tip and Toe",
    "hmx-by-hair-mechanics": "HMX by Hair Mechanics",
    "namastey": "Namastey",
    "zah-salons": "Zah Salons",
    "vikas-marwah": "Vikas Marwah",
    "toe-and-nail": "Toe & Nail",
    "femina-flaunt": "Femina Flaunt",
    "jcb-jean-claude-biguine": "JCB (Jean-Claude Biguine)",
    "enrich-salon": "Enrich Salon",
    "la-coiffure": "La Coiffure",
    "tattva-spas": "Tattva Spas",
    "kromakay-salon": "Kromakay Salon",
    "salon-ministry": "Salon Ministry",
    "zorro-salons": "Zorro Salons",
    "silk-and-salt": "Silk and Salt",
    "house-of-bumble": "House of Bumble",
    "monsoon-salon-pro": "Monsoon Salon Pro",
    "ftv-luxury-paris": "FTV Luxury Paris",
    "diamond": "Diamond",
    "bnc-bombay-nail-company": "BNC (Bombay Nail Company)",
    "studio-13": "Studio 13",
    "niks": "Niks",
    "apple-the-original": "Apple The Original",
    "the-first": "The First",
    "solastaa": "Solastaa",
    "blown": "Blown",
    "hair-castle": "Hair Castle",
    "marie-claire": "Marie Claire",
    "cut-and-style": "Cut and Style",
    "nailashes": "Nailashes",
    "hair-speak": "Hair Speak",
    "holy-nails": "Holy Nails",
    "veda-salons": "Veda Salons",
    "hair-poetry": "Hair Poetry",
    "the-glam-room": "The Glam Room",
    "barber-co": "Barber Co",
    "spark-spa": "Spark Spa",
    "plum-and-sugar": "Plum & Sugar",
    "lets-transform": "Let's Transform",
    "scent-salon": "Scent Salon",
    "aveda-x-nykaa": "Aveda x Nykaa",
    "bay-leaf-salon": "Bay Leaf Salon",
    "habibs": "Habib's",
    "the-sobo-nail-salon": "The SoBo Nail Salon",
    "zoei": "Zoei",
    "talons": "Talons",
    "subzcanvas": "Subzcanvas",
    "elixir-wellness": "Elixir Wellness",
    "naturals-salon": "Naturals Salon",
    "d5n": "D5N",
    "heavens-salon": "Heavens Salon",
    "the-black-dahlia": "The Black Dahlia",
    "aura-spa": "Aura Spa",
    "bodycraft-clinics": "Bodycraft Clinics",
    "lookwell-clinic": "LookWell Clinic",
    "iosis-spa-wellness": "IOSIS Spa & Wellness",
    "hipster-the-salon": "Hipster The Salon",
    "orchids-studio": "Orchids Studio",
    "aroma-thai-spa": "Aroma Thai Spa",
    "the-elements-spa": "The Elements Spa",
    "fingertips": "Fingertips",
    "dessange-salon-spa": "Dessange Salon & Spa",
    "toes-and-tresses": "Toes & Tresses",
    "victress": "Victress",
    "the-nail-hue": "The Nail Hue",
    "mary-cohr": "Mary Cohr",
    "wellness-co": "Wellness Co",
    "stylette-family": "Stylette Family",
    "the-revival-studio": "The Revival Studio",
    "bellissimo-nail-studio": "Bellissimo Nail Studio",
    "play-salon": "Play Salon",
    "colorcoats": "Colorcoats",
    "orom-salon": "Orom Salon",
    "hair-and-byond": "Hair & Byond",
    "the-good-skin-project": "The Good Skin Project",
    "luminous-studio-salon-spa": "Luminous Studio Salon & Spa",
    "hair-masters": "Hair Masters",
    "sensation-family": "Sensation Family",
    "dreams-family": "Dreams Family",
    "crois-en-toi-salon": "Crois En Toi Salon",
    "be-gorgeous": "Be Gorgeous",
    "glamour-garage": "Glamour Garage",
    "bs": "B&S",
    "marvel-hair-studio": "Marvel Hair Studio",
    "barberos": "Barberos",
    "kapils": "Kapils",
    "aa-hair-craft": "AA Hair Craft",
    "the-grooming-nation": "The Grooming Nation",
    "wisteria-salon": "Wisteria Salon",
    "all-good-things": "All Good Things",
    "head-town": "Head Town",
    "noi-tre": "Noi Tre",
    "like-as-me": "Like As Me",
    "bella-madonna": "Bella Madonna",
    "estilo": "Estilo",
    "am-to-am-salon": "Am To Am Salon",
    "ogloro": "O'Gloro",
    "nyc-salon": "NYC Salon",
    "color-cafe": "Color Cafe",
    "four-fountains": "Four Fountains",
    "jovi": "Jovi",
    "n-salon": "N Salon",
    "candid": "Candid",
    "tress-salon": "Tress Salon",
    "athenian-salon": "Athenian Salon",
    "cocoloon-salon": "Cocoloon Salon",
    "sallure-salon": "Sallure Salon",
    "thrix-co": "Thrix & Co",
    "merriment-salon": "Merriment Salon",
    "naksh-beauty-hub": "Naksh Beauty Hub",
    "eloras-pmu": "Eloras PMU",
    "rc-heavens": "RC Heavens",
    "hair-space": "Hair Space",
    "lakme": "Lakme",
    "a1-nail-art-studio": "A1 Nail Art Studio",
    "nail-edition": "Nail Edition",
    "dreadley-dreadlocks": "Dreadley Dreadlocks",
    "fingertips": "Fingertips",
    "truefitt-and-hill": "Truefitt & Hill",
  };